# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hash',
            field=models.BinaryField(default=None),
        ),
    ]
